package xyz.personalenrichment.domain.model;
// Generated Jul 9, 2016 8:25:03 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MatchPlayersJt generated by hbm2java
 */
@Entity
@Table(name = "match_players_jt", catalog = "domain_game")
public class MatchPlayersJt implements java.io.Serializable {

	private Integer idmatchPlayers;
	private Matches matches;
	private Users users;

	public MatchPlayersJt() {
	}

	public MatchPlayersJt(Matches matches, Users users) {
		this.matches = matches;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmatch_players", unique = true, nullable = false)
	public Integer getIdmatchPlayers() {
		return this.idmatchPlayers;
	}

	public void setIdmatchPlayers(Integer idmatchPlayers) {
		this.idmatchPlayers = idmatchPlayers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matches_id", nullable = false)
	public Matches getMatches() {
		return this.matches;
	}

	public void setMatches(Matches matches) {
		this.matches = matches;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "players_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
