package xyz.personalenrichment.domain.model;
// Generated Jul 9, 2016 8:25:03 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Matches generated by hbm2java
 */
@Entity
@Table(name = "matches", catalog = "domain_game")
public class Matches implements java.io.Serializable {

	private Integer idmatches;
	private Users users;
	private Date dateFinished;
	private @JsonIgnore Set<Moves> moveses = new HashSet<Moves>(0);
	private @JsonIgnore Set<MatchPlayersJt> matchPlayersJts = new HashSet<MatchPlayersJt>(0);

	public Matches() {
	}

	public Matches(Users users) {
		this.users = users;
	}

	public Matches(Users users, Date dateFinished, Set<Moves> moveses, Set<MatchPlayersJt> matchPlayersJts) {
		this.users = users;
		this.dateFinished = dateFinished;
		this.moveses = moveses;
		this.matchPlayersJts = matchPlayersJts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmatches", unique = true, nullable = false)
	public Integer getIdmatches() {
		return this.idmatches;
	}

	public void setIdmatches(Integer idmatches) {
		this.idmatches = idmatches;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "winner", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_finished", length = 10)
	public Date getDateFinished() {
		return this.dateFinished;
	}

	public void setDateFinished(Date dateFinished) {
		this.dateFinished = dateFinished;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matches")
	public Set<Moves> getMoveses() {
		return this.moveses;
	}

	public void setMoveses(Set<Moves> moveses) {
		this.moveses = moveses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matches")
	public Set<MatchPlayersJt> getMatchPlayersJts() {
		return this.matchPlayersJts;
	}

	public void setMatchPlayersJts(Set<MatchPlayersJt> matchPlayersJts) {
		this.matchPlayersJts = matchPlayersJts;
	}

}
