package xyz.personalenrichment.domain.model;
// Generated Jul 9, 2016 6:09:11 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Match generated by hbm2java
 */
@Entity
@Table(name = "match", catalog = "domain_game")
public class Match implements java.io.Serializable {

	private Integer idmatch;
	private @JsonIgnore User winner;
	private Date dateFinished;
	private byte[] preBoardState;
	private @JsonIgnore Set<Move> moves = new HashSet<Move>(0);
	private @JsonIgnore Set<MatchPlayerJt> matchPlayerJts = new HashSet<MatchPlayerJt>(0);

	public Match() {
	}

	public Match(byte[] preBoardState) {
		this.preBoardState = preBoardState;
	}

	public Match(User user, Date dateFinished, byte[] preBoardState, Set<Move> moves,
			Set<MatchPlayerJt> matchPlayerJts) {
		this.winner = user;
		this.dateFinished = dateFinished;
		this.preBoardState = preBoardState;
		this.moves = moves;
		this.matchPlayerJts = matchPlayerJts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmatch", unique = true, nullable = false)
	public Integer getIdmatch() {
		return this.idmatch;
	}

	public void setIdmatch(Integer idmatch) {
		this.idmatch = idmatch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "winner")
	public User getUser() {
		return this.winner;
	}

	public void setUser(User winner) {
		this.winner = winner;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_finished", length = 10)
	public Date getDateFinished() {
		return this.dateFinished;
	}

	public void setDateFinished(Date dateFinished) {
		this.dateFinished = dateFinished;
	}

	@Column(name = "pre_board_state", nullable = false)
	public byte[] getPreBoardState() {
		return this.preBoardState;
	}

	public void setPreBoardState(byte[] preBoardState) {
		this.preBoardState = preBoardState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "match")
	public Set<Move> getMoves() {
		return this.moves;
	}

	public void setMoves(Set<Move> moves) {
		this.moves = moves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "match")
	public Set<MatchPlayerJt> getMatchPlayerJts() {
		return this.matchPlayerJts;
	}

	public void setMatchPlayerJts(Set<MatchPlayerJt> matchPlayerJts) {
		this.matchPlayerJts = matchPlayerJts;
	}

}
