package xyz.personalenrichment.domain.model;
// Generated Jul 8, 2016 9:14:20 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Matches generated by hbm2java
 */
@Entity
@Table(name = "matches", catalog = "domain_game")
public class Matches implements java.io.Serializable {

	private Integer idmatches;
	private @JsonIgnore Users usersByPlayerBId;
	private @JsonIgnore Users usersByPlayerAId;
	private Byte winner;
	private Date dateFinished;
	private @JsonIgnore Set<Moves> moveses = new HashSet<Moves>(0);

	public Matches() {
	}

	public Matches(Users usersByPlayerBId, Users usersByPlayerAId) {
		this.usersByPlayerBId = usersByPlayerBId;
		this.usersByPlayerAId = usersByPlayerAId;
	}

	public Matches(Users usersByPlayerBId, Users usersByPlayerAId, Byte winner, Date dateFinished, Set<Moves> moveses) {
		this.usersByPlayerBId = usersByPlayerBId;
		this.usersByPlayerAId = usersByPlayerAId;
		this.winner = winner;
		this.dateFinished = dateFinished;
		this.moveses = moveses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmatches", unique = true, nullable = false)
	public Integer getIdmatches() {
		return this.idmatches;
	}

	public void setIdmatches(Integer idmatches) {
		this.idmatches = idmatches;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "player_b_id", nullable = false)
	public Users getUsersByPlayerBId() {
		return this.usersByPlayerBId;
	}

	public void setUsersByPlayerBId(Users usersByPlayerBId) {
		this.usersByPlayerBId = usersByPlayerBId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "player_a_id", nullable = false)
	public Users getUsersByPlayerAId() {
		return this.usersByPlayerAId;
	}

	public void setUsersByPlayerAId(Users usersByPlayerAId) {
		this.usersByPlayerAId = usersByPlayerAId;
	}

	@Column(name = "winner")
	public Byte getWinner() {
		return this.winner;
	}

	public void setWinner(Byte winner) {
		this.winner = winner;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_finished", length = 10)
	public Date getDateFinished() {
		return this.dateFinished;
	}

	public void setDateFinished(Date dateFinished) {
		this.dateFinished = dateFinished;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matches")
	public Set<Moves> getMoveses() {
		return this.moveses;
	}

	public void setMoveses(Set<Moves> moveses) {
		this.moveses = moveses;
	}

}
