package xyz.personalenrichment.domain.model;
// Generated Jul 9, 2016 6:09:11 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Move generated by hbm2java
 */
@Entity
@Table(name = "move", catalog = "domain_game")
public class Move implements java.io.Serializable {

	private int idmove;
	private @JsonIgnore Match match;
	private @JsonIgnore User user;
	private byte x;
	private byte y;
	private byte[] postBoardState;

	public Move() {
	}

	public Move(int idmove, Match match, User user, byte x, byte y) {
		this.idmove = idmove;
		this.match = match;
		this.user = user;
		this.x = x;
		this.y = y;
	}

	public Move(int idmove, Match match, User user, byte x, byte y, byte[] postBoardState) {
		this.idmove = idmove;
		this.match = match;
		this.user = user;
		this.x = x;
		this.y = y;
		this.postBoardState = postBoardState;
	}

	@Id

	@Column(name = "idmove", unique = true, nullable = false)
	public int getIdmove() {
		return this.idmove;
	}

	public void setIdmove(int idmove) {
		this.idmove = idmove;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "match_id", nullable = false)
	public Match getMatch() {
		return this.match;
	}

	public void setMatch(Match match) {
		this.match = match;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "player_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "x", nullable = false)
	public byte getX() {
		return this.x;
	}

	public void setX(byte x) {
		this.x = x;
	}

	@Column(name = "y", nullable = false)
	public byte getY() {
		return this.y;
	}

	public void setY(byte y) {
		this.y = y;
	}

	@Column(name = "post_board_state")
	public byte[] getPostBoardState() {
		return this.postBoardState;
	}

	public void setPostBoardState(byte[] postBoardState) {
		this.postBoardState = postBoardState;
	}

}
