package xyz.personalenrichment.domain.model;
// Generated Jul 9, 2016 6:09:11 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "domain_game", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class User implements java.io.Serializable {

	private Integer iduser;
	private String displayName;
	private String loginName;
	private String password;
	private String email;
	private @JsonIgnore Set<Move> moves = new HashSet<Move>(0);
	private @JsonIgnore Set<Match> matches = new HashSet<Match>(0);

	public User() {
	}

	public User(String displayName, String loginName, String password, String email) {
		this.displayName = displayName;
		this.loginName = loginName;
		this.password = password;
		this.email = email;
	}

	public User(String displayName, String loginName, String password, String email, Set<Move> moves,
			Set<Match> matches) {
		this.displayName = displayName;
		this.loginName = loginName;
		this.password = password;
		this.email = email;
		this.moves = moves;
		this.matches = matches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iduser", unique = true, nullable = false)
	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	@Column(name = "display_name", nullable = false, length = 127)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "login_name", nullable = false, length = 127)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Move> getMoves() {
		return this.moves;
	}

	public void setMoves(Set<Move> moves) {
		this.moves = moves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Match> getMatches() {
		return this.matches;
	}

	public void setMatches(Set<Match> matches) {
		this.matches = matches;
	}

}
